/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GriffithsMedicalCalendar2026RouteImport } from './routes/griffiths-medical-calendar-2026'
import { Route as IndexRouteImport } from './routes/index'

const GriffithsMedicalCalendar2026Route =
  GriffithsMedicalCalendar2026RouteImport.update({
    id: '/griffiths-medical-calendar-2026',
    path: '/griffiths-medical-calendar-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/griffiths-medical-calendar-2026': typeof GriffithsMedicalCalendar2026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/griffiths-medical-calendar-2026': typeof GriffithsMedicalCalendar2026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/griffiths-medical-calendar-2026': typeof GriffithsMedicalCalendar2026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/griffiths-medical-calendar-2026'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/griffiths-medical-calendar-2026'
  id: '__root__' | '/' | '/griffiths-medical-calendar-2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GriffithsMedicalCalendar2026Route: typeof GriffithsMedicalCalendar2026Route
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/griffiths-medical-calendar-2026': {
      id: '/griffiths-medical-calendar-2026'
      path: '/griffiths-medical-calendar-2026'
      fullPath: '/griffiths-medical-calendar-2026'
      preLoaderRoute: typeof GriffithsMedicalCalendar2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GriffithsMedicalCalendar2026Route: GriffithsMedicalCalendar2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
